//! Composer autoload support.
//!
//! This module handles parsing `composer.json` to extract PSR-4 autoload
//! mappings, and resolving fully-qualified PHP class names to file paths
//! on disk using those mappings.
//!
//! It also parses `autoload_files.php` (generated by Composer) to discover
//! files that contain global function and constant definitions.
//!
//! # PSR-4 Resolution
//!
//! Given a mapping like `"Klarna\\" => "src/Klarna/"`, a class name like
//! `Klarna\Customer` is resolved by:
//!   1. Stripping the matching prefix (`Klarna\`) from the class name
//!   2. Converting remaining namespace separators to directory separators
//!   3. Appending `.php`
//!   4. Prepending the mapped base directory
//!
//! Result: `<workspace>/src/Klarna/Customer.php`

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::types::PhpVersion;

/// A single PSR-4 namespace-to-directory mapping.
///
/// PSR-4 mappings are sourced exclusively from the project's own
/// `composer.json` (`autoload` and `autoload-dev` sections).  Vendor
/// packages are not included — the Composer classmap is the sole source
/// of truth for vendor code.
#[derive(Debug, Clone)]
pub struct Psr4Mapping {
    /// The namespace prefix, always ending with `\` (e.g. `"Klarna\"`).
    pub prefix: String,
    /// The base directory path relative to the workspace root (e.g. `"src/Klarna/"`).
    pub base_path: String,
}

/// Parse a `composer.json` file at the given workspace root and extract all
/// PSR-4 autoload mappings from both `autoload` and `autoload-dev` sections.
///
/// Only the project's own mappings are returned.  Vendor package mappings
/// (from `vendor/composer/autoload_psr4.php`) are deliberately not loaded —
/// the Composer classmap is the sole source of truth for vendor code.  If the
/// classmap is missing or stale, vendor classes will fail to resolve visibly
/// instead of being silently papered over by PSR-4, making the problem
/// obvious to the user (fix: run `composer dump-autoload`).
///
/// Returns `(mappings, vendor_dir)` where `vendor_dir` is the configured
/// `config.vendor-dir` (defaulting to `"vendor"`).  Both values come from
/// the same parse of `composer.json` so the file is only read once.
///
/// Returns an empty `Vec` and `"vendor"` if the file doesn't exist, can't
/// be read, or contains no PSR-4 mappings.
pub fn parse_composer_json(workspace_root: &Path) -> (Vec<Psr4Mapping>, String) {
    let composer_path = workspace_root.join("composer.json");
    let content = match fs::read_to_string(&composer_path) {
        Ok(c) => c,
        Err(_) => return (Vec::new(), "vendor".to_string()),
    };

    let json: serde_json::Value = match serde_json::from_str(&content) {
        Ok(v) => v,
        Err(_) => return (Vec::new(), "vendor".to_string()),
    };

    let vendor_dir = get_vendor_dir(&json);

    let mut mappings = Vec::new();

    // Extract from both "autoload" and "autoload-dev" sections
    for section_key in &["autoload", "autoload-dev"] {
        if let Some(section) = json.get(section_key)
            && let Some(psr4) = section.get("psr-4")
            && let Some(psr4_obj) = psr4.as_object()
        {
            for (prefix, paths) in psr4_obj {
                extract_psr4_entries(prefix, paths, &mut mappings);
            }
        }
    }

    // Sort by prefix length descending so longest-prefix-first matching works
    mappings.sort_by(|a, b| b.prefix.len().cmp(&a.prefix.len()));

    (mappings, vendor_dir)
}

/// Read the configured vendor directory from a parsed `composer.json` value.
///
/// Looks at `config.vendor-dir`; defaults to `"vendor"` when absent.
pub(crate) fn get_vendor_dir(composer_json: &serde_json::Value) -> String {
    composer_json
        .get("config")
        .and_then(|c| c.get("vendor-dir"))
        .and_then(|v| v.as_str())
        .map(|s| s.trim_end_matches('/').to_string())
        .unwrap_or_else(|| "vendor".to_string())
}

/// Read the configured bin directory from a parsed `composer.json` value.
///
/// Looks at `config.bin-dir`; defaults to `"<vendor-dir>/bin"` when absent,
/// where `<vendor-dir>` is itself resolved via [`get_vendor_dir`].
pub(crate) fn get_bin_dir(composer_json: &serde_json::Value) -> String {
    if let Some(explicit) = composer_json
        .get("config")
        .and_then(|c| c.get("bin-dir"))
        .and_then(|v| v.as_str())
    {
        explicit.trim_end_matches('/').to_string()
    } else {
        format!("{}/bin", get_vendor_dir(composer_json))
    }
}

/// Parse `<vendor>/composer/autoload_classmap.php` and return a mapping
/// from fully-qualified class name to file path (relative to the workspace
/// root).
///
/// This file is generated by `composer install` / `composer dump-autoload`
/// and maps class names directly to their defining files.  When the user
/// runs `composer install -o` (optimised autoloader), Composer converts
/// all PSR-0 and PSR-4 mappings into a classmap, giving us complete
/// coverage of every loadable class.
///
/// The file contains lines like:
/// ```text
///     'AWS\\CRT\\Auth\\AwsCredentials' => $vendorDir . '/aws/aws-crt-php/src/AWS/CRT/Auth/AwsCredentials.php',
///     'App\\Models\\User' => $baseDir . '/app/Models/User.php',
/// ```
///
/// `$vendorDir` is resolved relative to the workspace root using the
/// configured vendor directory.  `$baseDir` is the workspace root itself.
///
/// Returns an empty `HashMap` if the file does not exist or cannot be
/// parsed.
pub fn parse_autoload_classmap(
    workspace_root: &Path,
    vendor_dir: &str,
) -> HashMap<String, PathBuf> {
    let autoload_path = workspace_root
        .join(vendor_dir)
        .join("composer")
        .join("autoload_classmap.php");

    let content = match fs::read_to_string(&autoload_path) {
        Ok(c) => c,
        Err(_) => return HashMap::new(),
    };

    let mut classmap = HashMap::new();

    for line in content.lines() {
        let trimmed = line.trim();

        // Match lines of the form:
        //   'Fully\\Qualified\\ClassName' => $vendorDir . '/path/to/File.php',
        //   'Fully\\Qualified\\ClassName' => $baseDir . '/path/to/File.php',
        if let Some(rest) = trimmed.strip_prefix('\'')
            && let Some(arrow_pos) = rest.find("' => ")
        {
            // Unescape PHP single-quoted string escapes:
            //   \\  →  \
            //   \'  →  '
            let class_name = rest[..arrow_pos]
                .replace("\\\\'", "'")
                .replace("\\\\", "\\");

            let rhs = rest[arrow_pos + "' => ".len()..]
                .trim()
                .trim_end_matches(',');

            if let Some(relative_path) = resolve_autoload_path_entry(rhs, vendor_dir) {
                classmap.insert(class_name, workspace_root.join(&relative_path));
            }
        }
    }

    classmap
}

/// Resolve a single path entry from `autoload_psr4.php`.
///
/// Handles `$vendorDir . '/path'` and `$baseDir . '/path'`.
fn resolve_autoload_path_entry(entry: &str, vendor_dir: &str) -> Option<String> {
    let entry = entry.trim();

    if let Some(rest) = entry.strip_prefix("$vendorDir . '") {
        // $vendorDir . '/org/pkg/src'
        let path = rest.strip_suffix('\'')?;
        let path = path.strip_prefix('/').unwrap_or(path);
        Some(format!("{}/{}", vendor_dir, path))
    } else if let Some(rest) = entry.strip_prefix("$baseDir . '") {
        // $baseDir . '/lib'
        let path = rest.strip_suffix('\'')?;
        let path = path.strip_prefix('/').unwrap_or(path);
        Some(path.to_string())
    } else {
        None
    }
}

/// Parse `<vendor>/composer/autoload_files.php` and return the resolved
/// file paths.
///
/// This file is generated by `composer install` / `composer dump-autoload`
/// and lists files that should be eagerly loaded — typically containing
/// global function definitions, `define()` calls, and similar bootstrap
/// code.
///
/// The file contains lines like:
/// ```text
///     'hash' => $vendorDir . '/org/pkg/src/functions.php',
///     'hash' => $baseDir . '/app/Http/helpers.php',
/// ```
///
/// `$vendorDir` is resolved relative to the workspace root using the
/// configured vendor directory.  `$baseDir` is the workspace root itself.
///
/// Returns an empty `Vec` if the file does not exist or cannot be parsed.
pub fn parse_autoload_files(workspace_root: &Path, vendor_dir: &str) -> Vec<PathBuf> {
    let autoload_path = workspace_root
        .join(vendor_dir)
        .join("composer")
        .join("autoload_files.php");

    let content = match fs::read_to_string(&autoload_path) {
        Ok(c) => c,
        Err(_) => return Vec::new(),
    };

    let mut files = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();

        // Match lines of the form:  'hash' => $vendorDir . '/path/to/file.php',
        //                       or: 'hash' => $baseDir . '/path/to/file.php',
        // We look for `=> $vendorDir` or `=> $baseDir` after the hash key.
        if let Some(arrow_pos) = trimmed.find("=> ") {
            let rhs = trimmed[arrow_pos + 3..].trim().trim_end_matches(',');

            if let Some(base_path) = resolve_autoload_path_entry(rhs, vendor_dir) {
                let full_path = workspace_root.join(&base_path);
                if full_path.is_file() {
                    files.push(full_path);
                }
            }
        }
    }

    files
}

/// Extract PSR-4 entries from a single prefix → path(s) pair.
///
/// The value can be either a string (`"src/"`) or an array of strings
/// (`["src/", "lib/"]`).
fn extract_psr4_entries(prefix: &str, paths: &serde_json::Value, mappings: &mut Vec<Psr4Mapping>) {
    // Normalise the prefix: ensure it ends with `\`
    let normalised_prefix = if prefix.ends_with('\\') {
        prefix.to_string()
    } else if prefix.is_empty() {
        // Empty prefix means "fallback" / root namespace
        String::new()
    } else {
        format!("{}\\", prefix)
    };

    match paths {
        serde_json::Value::String(path) => {
            mappings.push(Psr4Mapping {
                prefix: normalised_prefix.clone(),
                base_path: normalise_path(path),
            });
        }
        serde_json::Value::Array(arr) => {
            for entry in arr {
                if let Some(path) = entry.as_str() {
                    mappings.push(Psr4Mapping {
                        prefix: normalised_prefix.clone(),
                        base_path: normalise_path(path),
                    });
                }
            }
        }
        _ => {}
    }
}

/// Normalise a directory path: ensure it uses forward slashes and ends with `/`.
pub fn normalise_path(path: &str) -> String {
    let p = path.replace('\\', "/");
    if p.ends_with('/') || p.is_empty() {
        p
    } else {
        format!("{}/", p)
    }
}

/// Resolve a fully-qualified PHP class name to a file path using PSR-4 mappings.
///
/// The `class_name` should be the namespace-qualified name (e.g.
/// `"Klarna\\Customer"` or `"Klarna\\Rest\\Order"`). A leading `\` is
/// stripped if present (PHP fully-qualified syntax).
///
/// Returns the first path that exists on disk, or `None` if no mapping
/// matches or the resolved file doesn't exist.
pub fn resolve_class_path(
    mappings: &[Psr4Mapping],
    workspace_root: &Path,
    class_name: &str,
) -> Option<PathBuf> {
    let name = class_name;

    // Skip built-in type keywords that are never real classes
    if is_builtin_type(name) {
        return None;
    }

    // Try each mapping (already sorted longest-prefix-first)
    for mapping in mappings {
        let relative = if mapping.prefix.is_empty() {
            // Empty prefix matches everything (root namespace fallback)
            Some(name)
        } else {
            name.strip_prefix(&mapping.prefix)
        };

        if let Some(relative_class) = relative {
            // Convert namespace separators to directory separators
            let relative_path = relative_class.replace('\\', "/");
            let file_path = workspace_root
                .join(&mapping.base_path)
                .join(format!("{}.php", relative_path));

            if file_path.is_file() {
                return Some(file_path);
            }
        }
    }

    None
}

/// Check if a name is a PHP built-in type (not a class).
fn is_builtin_type(name: &str) -> bool {
    matches!(
        name,
        "$this"
            | "self"
            | "static"
            | "parent"
            | "string"
            | "int"
            | "float"
            | "bool"
            | "array"
            | "object"
            | "mixed"
            | "void"
            | "never"
            | "null"
            | "true"
            | "false"
            | "callable"
            | "iterable"
    )
}

/// Extract file paths from `require_once` statements in PHP source content.
///
/// Handles both the statement form and the function-like form:
/// ```text
///     require_once 'Trustly/exceptions.php';
///     require_once('Trustly/Data/data.php');
/// ```
///
/// Only bare string literals are supported — concatenations, variables,
/// and other dynamic expressions are silently skipped.
///
/// Returns the raw path strings exactly as written in the source (e.g.
/// `"Trustly/exceptions.php"`).  The caller is responsible for resolving
/// them relative to the file's directory.
pub fn extract_require_once_paths(content: &str) -> Vec<String> {
    let mut paths = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();

        // Quick reject: line must start with `require_once`.
        // (We don't support `require_once` buried in complex expressions.)
        if !trimmed.starts_with("require_once") {
            continue;
        }

        let rest = trimmed["require_once".len()..].trim_start();

        // Strip optional parentheses: `require_once('...')` → `'...'`
        // Also handles `require_once '...'` without parens.
        let rest = if let Some(inner) = rest.strip_prefix('(') {
            // Find matching closing paren
            if let Some(end) = inner.rfind(')') {
                inner[..end].trim()
            } else {
                continue;
            }
        } else {
            rest
        };

        // Strip trailing semicolon
        let rest = rest.trim_end_matches(';').trim();

        // Extract string literal — single or double quoted
        let path = if (rest.starts_with('\'') && rest.ends_with('\''))
            || (rest.starts_with('"') && rest.ends_with('"'))
        {
            &rest[1..rest.len() - 1]
        } else {
            // Not a simple string literal — skip
            continue;
        };

        if !path.is_empty() {
            paths.push(path.to_string());
        }
    }

    paths
}

/// Detect `.phar` archive references in a PHP bootstrap file.
///
/// Scans the file content for patterns like:
///
/// ```text
/// require 'phar://' . __DIR__ . '/phpstan.phar/vendor/autoload.php';
/// $filepath = 'phar://' . __DIR__ . '/phpstan.phar/src/' . $filename . '.php';
/// ```
///
/// Returns the absolute paths of all `.phar` files referenced in the
/// content, resolved relative to `file_dir` (the directory containing
/// the bootstrap file).
///
/// This is intentionally lenient: it looks for any `__DIR__` + string
/// concatenation that mentions a `.phar` file, regardless of the
/// surrounding PHP structure.  False positives are harmless (the phar
/// parser will reject non-phar files), and false negatives are
/// acceptable (users can always extract the phar manually).
pub fn detect_phar_references(content: &str, file_dir: &Path) -> Vec<PathBuf> {
    let mut phars = Vec::new();
    let mut seen = std::collections::HashSet::new();

    for line in content.lines() {
        // Look for lines containing both `__DIR__` and `.phar`.
        if !line.contains("__DIR__") || !line.contains(".phar") {
            continue;
        }

        // Extract the phar filename from string fragments like:
        //   '/phpstan.phar/vendor/autoload.php'
        //   '/phpstan.phar/src/'
        // We look for quoted strings containing `.phar` and extract
        // the path up to (and including) the `.phar` extension.
        for quote in [b'\'', b'"'] {
            let bytes = line.as_bytes();
            let mut i = 0;
            while i < bytes.len() {
                if bytes[i] == quote {
                    // Find the closing quote.
                    if let Some(end) = bytes[i + 1..].iter().position(|&b| b == quote) {
                        let fragment = &line[i + 1..i + 1 + end];
                        if let Some(phar_end) = fragment.find(".phar") {
                            // Extract the relative path: e.g. "/phpstan.phar"
                            let rel = &fragment[..phar_end + 5]; // +5 for ".phar"
                            let rel = rel.trim_start_matches('/');
                            if !rel.is_empty() {
                                let phar_path = file_dir.join(rel);
                                if phar_path.is_file() && seen.insert(phar_path.clone()) {
                                    phars.push(phar_path);
                                }
                            }
                        }
                        i += 1 + end + 1;
                    } else {
                        i += 1;
                    }
                } else {
                    i += 1;
                }
            }
        }
    }

    phars
}

/// Discover PHP subproject roots inside a workspace directory.
///
/// When the workspace root itself has no `composer.json`, this function
/// walks subdirectories looking for `composer.json` files using the
/// `ignore` crate for gitignore-aware walking.  Each directory that
/// contains a `composer.json` is returned as a subproject root paired
/// with its configured vendor directory name.  Once a `composer.json`
/// is found in a directory, its children are not descended into (they
/// belong to that project's source tree, not to a separate subproject).
///
/// The walk respects `.gitignore` at every level, so vendor directories
/// that are gitignored (the common case in monorepos) are automatically
/// skipped along with any other noise the user has excluded.  Hidden
/// directories (starting with `.`) are also skipped.
///
/// This enables monorepo support: a workspace like
///
/// ```text
/// monorepo/               ← workspace root (no composer.json)
/// ├── project-a/
/// │   ├── composer.json   ← discovered
/// │   ├── src/
/// │   └── vendor/
/// └── packages/
///     └── project-b/
///         ├── composer.json  ← discovered (depth 2)
///         └── src/
/// ```
///
/// returns `[(monorepo/project-a, "vendor"), (monorepo/packages/project-b, "vendor")]`.
pub fn discover_subproject_roots(workspace_root: &Path) -> Vec<(PathBuf, String)> {
    use ignore::WalkBuilder;
    use std::collections::HashSet;

    let mut candidates: Vec<PathBuf> = Vec::new();

    let walker = WalkBuilder::new(workspace_root)
        .git_ignore(true)
        .git_global(true)
        .git_exclude(true)
        .hidden(true)
        .parents(true)
        .ignore(true)
        // Sort to get deterministic output
        .sort_by_file_name(|a, b| a.cmp(b))
        .build();

    for entry in walker.flatten() {
        let path = entry.path();
        // We only care about files named "composer.json"
        if !path.is_file() {
            continue;
        }
        if path.file_name().and_then(|n| n.to_str()) != Some("composer.json") {
            continue;
        }
        // The subproject root is the parent directory of composer.json
        if let Some(parent) = path.parent() {
            // Skip the workspace root itself — the caller already checked
            // that it has no composer.json (or has one and took the
            // single-project path).
            if parent == workspace_root {
                continue;
            }
            candidates.push(parent.to_path_buf());
        }
    }

    // Filter out nested roots: if both `packages/foo` and
    // `packages/foo/subdir` contain composer.json, only keep the
    // outermost one.  Sort by path length so we process shorter
    // (shallower) paths first.
    candidates.sort_by_key(|p| p.as_os_str().len());

    let mut roots: Vec<(PathBuf, String)> = Vec::new();
    let mut root_set: HashSet<PathBuf> = HashSet::new();

    for candidate in &candidates {
        // Check if this candidate is inside an already-accepted root
        let is_nested = root_set.iter().any(|root| candidate.starts_with(root));
        if is_nested {
            continue;
        }

        // Read the vendor dir name from this subproject's composer.json
        let composer_path = candidate.join("composer.json");
        let vendor_dir = if let Ok(content) = fs::read_to_string(&composer_path) {
            if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
                get_vendor_dir(&json)
            } else {
                "vendor".to_string()
            }
        } else {
            "vendor".to_string()
        };

        root_set.insert(candidate.clone());
        roots.push((candidate.clone(), vendor_dir));
    }

    roots
}

/// Detect the target PHP version from a project's `composer.json`.
///
/// Checks two locations in order:
///   1. `config.platform.php` — an explicit platform override
///      (e.g. `"8.3.1"` → 8.3).
///   2. `require.php` — the version constraint from the dependency
///      list (e.g. `"^8.4"` → 8.4).
///
/// Returns `None` when `composer.json` is missing, unreadable, or does
/// not contain a PHP version constraint.  The caller should fall back to
/// [`PhpVersion::default`] in that case.
pub fn detect_php_version(workspace_root: &Path) -> Option<PhpVersion> {
    let composer_path = workspace_root.join("composer.json");
    let content = fs::read_to_string(composer_path).ok()?;
    let json: serde_json::Value = serde_json::from_str(&content).ok()?;

    // 1. config.platform.php — exact version string like "8.3.1"
    if let Some(platform_php) = json
        .get("config")
        .and_then(|c| c.get("platform"))
        .and_then(|p| p.get("php"))
        .and_then(|v| v.as_str())
        && let Some(ver) = PhpVersion::from_composer_constraint(platform_php)
    {
        return Some(ver);
    }

    // 2. require.php — constraint string like "^8.4", ">=8.0"
    if let Some(require_php) = json
        .get("require")
        .and_then(|r| r.get("php"))
        .and_then(|v| v.as_str())
        && let Some(ver) = PhpVersion::from_composer_constraint(require_php)
    {
        return Some(ver);
    }

    None
}

/// Check whether a package name appears in `composer.json`'s `require-dev`.
///
/// Matches the package name exactly (e.g.
/// `"friendsofphp/php-cs-fixer"`, `"squizlabs/php_codesniffer"`).
pub(crate) fn has_require_dev(composer_json: &serde_json::Value, package: &str) -> bool {
    composer_json
        .get("require-dev")
        .and_then(|rd| rd.as_object())
        .is_some_and(|rd| rd.contains_key(package))
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── get_vendor_dir ──────────────────────────────────────────────

    #[test]
    fn vendor_dir_default() {
        let json: serde_json::Value = serde_json::from_str("{}").unwrap();
        assert_eq!(get_vendor_dir(&json), "vendor");
    }

    #[test]
    fn vendor_dir_explicit() {
        let json: serde_json::Value =
            serde_json::from_str(r#"{"config": {"vendor-dir": "lib"}}"#).unwrap();
        assert_eq!(get_vendor_dir(&json), "lib");
    }

    #[test]
    fn vendor_dir_strips_trailing_slash() {
        let json: serde_json::Value =
            serde_json::from_str(r#"{"config": {"vendor-dir": "lib/"}}"#).unwrap();
        assert_eq!(get_vendor_dir(&json), "lib");
    }

    // ── get_bin_dir ─────────────────────────────────────────────────

    #[test]
    fn bin_dir_default_follows_vendor_dir() {
        let json: serde_json::Value = serde_json::from_str("{}").unwrap();
        assert_eq!(get_bin_dir(&json), "vendor/bin");
    }

    #[test]
    fn bin_dir_default_with_custom_vendor_dir() {
        let json: serde_json::Value =
            serde_json::from_str(r#"{"config": {"vendor-dir": "lib"}}"#).unwrap();
        assert_eq!(get_bin_dir(&json), "lib/bin");
    }

    #[test]
    fn bin_dir_explicit() {
        let json: serde_json::Value =
            serde_json::from_str(r#"{"config": {"bin-dir": "bin"}}"#).unwrap();
        assert_eq!(get_bin_dir(&json), "bin");
    }

    #[test]
    fn bin_dir_explicit_overrides_vendor_dir() {
        let json: serde_json::Value =
            serde_json::from_str(r#"{"config": {"vendor-dir": "lib", "bin-dir": "tools/bin"}}"#)
                .unwrap();
        assert_eq!(get_bin_dir(&json), "tools/bin");
    }

    #[test]
    fn bin_dir_strips_trailing_slash() {
        let json: serde_json::Value =
            serde_json::from_str(r#"{"config": {"bin-dir": "bin/"}}"#).unwrap();
        assert_eq!(get_bin_dir(&json), "bin");
    }
}
